# Generated by Django 3.2.6 on 2021-08-09 08:06

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('loan_id', models.CharField(max_length=12, verbose_name='Идентификатор кредита')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('married', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=100)),
                ('dependents', models.BooleanField(default=False, verbose_name='Есть ли иждивенцы')),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=100)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('applicant_income', models.PositiveIntegerField(default=0, verbose_name='Доход')),
                ('coapplicant_income', models.PositiveIntegerField(default=0, verbose_name='Доход поручителя')),
                ('loan_amount', models.PositiveIntegerField(default=0, verbose_name='Размер кредита')),
                ('loan_amount_term', models.IntegerField(verbose_name='Срок займа в днях')),
                ('credit_history', models.BooleanField(default=False, verbose_name='Кредитная история')),
                ('property_area', models.CharField(choices=[('urban', 'urban'), ('rural', 'rural')], max_length=100)),
                ('loan_status', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=100)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_model', models.BinaryField(verbose_name='ML модель')),
                ('model_name', models.CharField(max_length=20, verbose_name='Название модели')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmed_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfUserActions',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_task', models.BooleanField(verbose_name='Ответ celery')),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baseuser', verbose_name='Профиль заемщика')),
            ],
        ),
    ]
