# Generated by Django 3.2.6 on 2021-08-14 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=12, verbose_name='Идентификатор кредита')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('married', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=100)),
                ('dependents', models.CharField(max_length=12, verbose_name='Количество иждивенцов')),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=100)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('applicant_income', models.FloatField(default=0, verbose_name='Доход')),
                ('coapplicant_income', models.FloatField(default=0, verbose_name='Доход поручителя')),
                ('loan_amount', models.FloatField(default=0, verbose_name='Размер кредита')),
                ('loan_amount_term', models.FloatField(verbose_name='Срок займа в днях')),
                ('credit_history', models.CharField(max_length=12, verbose_name='Кредитная история')),
                ('property_area', models.CharField(choices=[('urban', 'urban'), ('rural', 'rural')], max_length=100)),
                ('loan_status', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Базовый пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='MLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_model', models.BinaryField(verbose_name='ML модель')),
                ('model_name', models.CharField(max_length=20, verbose_name='Название модели')),
            ],
            options={
                'verbose_name': 'ML модель',
                'verbose_name_plural': 'ML модели',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('confirmed_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='HistoryOfUserActions',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_task', models.BooleanField(verbose_name='Ответ celery')),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.baseuser', verbose_name='Профиль заемщика')),
            ],
            options={
                'verbose_name': 'История транзацкий',
                'verbose_name_plural': 'Истории транзацкий',
            },
        ),
    ]
