# Generated by Django 3.2.6 on 2021-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210814_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='loan_status',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=100),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'urban'), ('Rural', 'rural')], max_length=100),
        ),
    ]
