# Generated by Django 3.2.6 on 2021-08-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210809_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='applicant_income',
            field=models.FloatField(default=0, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='coapplicant_income',
            field=models.FloatField(default=0, verbose_name='Доход поручителя'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='loan_amount',
            field=models.FloatField(default=0, verbose_name='Размер кредита'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='loan_amount_term',
            field=models.FloatField(verbose_name='Срок займа в днях'),
        ),
    ]
