# Generated by Django 3.2.6 on 2021-08-16 16:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210814_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodels',
            name='ml_model',
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='model_file',
            field=models.FileField(default=django.utils.timezone.now, help_text='Только pkl файлы', upload_to='sentiment/prediction/models/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pkl'])], verbose_name='ML Модель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mlmodels',
            name='model_name',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
    ]
