# Generated by Django 3.2.6 on 2021-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210810_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='credit_history',
            field=models.CharField(max_length=12, verbose_name='Кредитная история'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='dependents',
            field=models.CharField(max_length=12, verbose_name='Количество иждивенцов'),
        ),
    ]
